name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '15.2.0', '15.11.0' ]

    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - run: uname -a
      - run: node -v
      - run: node server.js &
      - run: chmod +x ./run.sh
      - run: ./run.sh
